#!/usr/bin/python

import requests
from optparse import OptionParser
from blocknet.bin.fabricnetwork import start


def main():

    try:

        if __name__ == "__main__":
            start()
    except KeyboardInterrupt:
        print("\n")
        pass


main()
