

name: ${ORG}
version: 1.0.0
client:
  organization: ${ORG}
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  ${ORG}:
    mspid: ${MSP}
    peers:

    - ${PEER0}
            
    - ${PEER1}
            
    certificateAuthorities:
    - ${CA}
peers:

  ${PEER0}:
    url: grpcs://localhost:${P0PORT}
    tlsCACerts:
      pem: |
        ${PEERPEM}
    grpcOptions:
      ssl-target-name-override: ${PEER0}
      hostnameOverride: ${PEER0}
            
  ${PEER1}:
    url: grpcs://localhost:${P1PORT}
    tlsCACerts:
      pem: |
        ${PEERPEM}
    grpcOptions:
      ssl-target-name-override: ${PEER1}
      hostnameOverride: ${PEER1}
            
certificateAuthorities:
  ${CA}:
    url: https://localhost:${CAPORT}
    caName: ${CANAME}
    tlsCACerts:
      pem: |
        ${CAPEM}
    httpOptions:
      verify: false

        