
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

            
  - &SDFSDFSDF

  	Name: SDFSDFSDF

  	ID: SDFSDFSDFMSP

  	MSPDir: crypto-config/peerOrganizations/sdfsdfsdf.com/msp


  	Policies:
 	     Readers:
				   Type: Signature
				   Rule: "OR('SDFSDFSDFMSP.admin','SDFSDFSDFMSP.peer','SDFSDFSDFMSP.client')"
 	     Writers:
				   Type: Signature
				   Rule: "OR('SDFSDFSDFMSP.admin','SDFSDFSDFMSP.peer','SDFSDFSDFMSP.client')"
 	     Admins:
				   Type: Signature
				   Rule: "OR('SDFSDFSDFMSP.admin')"

  	AnchorPeers:


			- Host: peer0.sdfsdfsdf.com
			  Port: 7051


  - &Orderer

  	Name: Orderer

  	ID: OrdererMSP

  	MSPDir: crypto-config/ordererOrganizations/sdfsdfsdf.com/msp


  	Policies:
 	     Readers:
				   Type: Signature
				   Rule: "OR('OrdererMSP.member')"
 	     Writers:
				   Type: Signature
				   Rule: "OR('OrdererMSP.member')"
 	     Admins:
				   Type: Signature
				   Rule: "OR('OrdererMSP.admin')"


  - &adada

  	Name: adada

  	ID: adadaMSP

  	MSPDir: crypto-config/peerOrganizations/adada.com/msp


  	Policies:
 	     Readers:
				   Type: Signature
				   Rule: "OR('adadaMSP.admin','adadaMSP.peer','adadaMSP.client')"
 	     Writers:
				   Type: Signature
				   Rule: "OR('adadaMSP.admin','adadaMSP.client')"
 	     Admins:
				   Type: Signature
				   Rule: "OR('adadaMSP.admin')"

  	AnchorPeers:


			- Host: peer0.adada.com
			  Port: 7051


  - &adadad

  	Name: adadad

  	ID: adadadMSP

  	MSPDir: crypto-config/peerOrganizations/adadad.com/msp


  	Policies:
 	     Readers:
				   Type: Signature
				   Rule: "OR('adadadMSP.admin','adadadMSP.peer','adadadMSP.client')"
 	     Writers:
				   Type: Signature
				   Rule: "OR('adadadMSP.admin','adadadMSP.client')"
 	     Admins:
				   Type: Signature
				   Rule: "OR('adadadMSP.admin')"

  	AnchorPeers:


			- Host: peer0.adadad.com
			  Port: 7051



################################################################################
#
#   SECTION: Capabilities
#
#   - This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.
    # Set the value of the capability to true to require it.
    Channel: &ChannelCapabilities


		  V1_4_4: true

		  V1_4_2: false

		  V1_3: false

		  V1_2: false

		  V1_1: false

    # Orderer capabilities apply only to the orderers, and may be safely
    # used with prior release peers.
    # Set the value of the capability to true to require it.
    Orderer: &OrdererCapabilities


		  V1_4_4: true

		  V1_4_2: false

		  V1_3: false

		  V1_2: false

		  V1_1: false

    # Application capabilities apply only to the peer network, and may be safely
    # used with prior release orderers.
    # Set the value of the capability to true to require it.
    Application: &ApplicationCapabilities


		  V1_4_4: true

		  V1_4_2: false

		  V1_3: false

		  V1_2: false

		  V1_1: false

        

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        
 	     Readers:
				   Type: ImplicitMeta
				   Rule: "ANY Readers"
 	     Writers:
				   Type: ImplicitMeta
				   Rule: "ANY Writers"
 	     Admins:
				   Type: ImplicitMeta
				   Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities
        


################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo","kafka"  and "etcdraft"
    OrdererType: etcdraft

    Addresses:
        - orderer.sdfsdfsdf.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:


        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB
        

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # EtcdRaft defines configuration which must be set when the "etcdraft"
    # orderertype is chosen.
    EtcdRaft:
        # The set of Raft replicas for this network. For the etcd/raft-based
        # implementation, we expect every replica to also be an OSN. Therefore,
        # a subset of the host:port items enumerated in this list should be
        # replicated under the Orderer.Addresses key above.
        Consenters:
            
            - Host: orderer.sdfsdfsdf.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer.sdfsdfsdf.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer.sdfsdfsdf.com/tls/server.crt
            
            - Host: orderer1.sdfsdfsdf.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer1.sdfsdfsdf.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer1.sdfsdfsdf.com/tls/server.crt
            
            - Host: orderer2.sdfsdfsdf.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer2.sdfsdfsdf.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer2.sdfsdfsdf.com/tls/server.crt
            
            - Host: orderer3.sdfsdfsdf.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer3.sdfsdfsdf.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer3.sdfsdfsdf.com/tls/server.crt
            
            - Host: orderer4.sdfsdfsdf.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer4.sdfsdfsdf.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer4.sdfsdfsdf.com/tls/server.crt
            
            - Host: orderer5.sdfsdfsdf.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer5.sdfsdfsdf.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer5.sdfsdfsdf.com/tls/server.crt
            
    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        
 	     Readers:
				   Type: ImplicitMeta
				   Rule: "ANY Readers"
 	     Writers:
				   Type: ImplicitMeta
				   Rule: "ANY Writers"
 	     Admins:
				   Type: ImplicitMeta
				   Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        
 	     BlockValidation:
				   Type: ImplicitMeta
				   Rule: "ANY Writers"

                

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        
 	     Readers:
				   Type: ImplicitMeta
				   Rule: "ANY Readers"
 	     Writers:
				   Type: ImplicitMeta
				   Rule: "ANY Writers"
 	     Admins:
				   Type: ImplicitMeta
				   Rule: "MAJORITY Admins"

    # Capabilities describes the channel level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    Capabilities:
        <<: *ChannelCapabilities


################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    SdfsdfsdfGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            sdfsdfsf:
                Organizations:
                
                		 - * SDFSDFSDF 
                		 - * ADADA 
                		 - * ADADAD 
    SdfsdfsdfChannel:
        Consortium: sdfsdfsf
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                
                		 - * SDFSDFSDF 
                		 - * ADADA 
                		 - * ADADAD 
            Capabilities:
                <<: *ApplicationCapabilities

    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                    
            		- Host: orderer.sdfsdfsdf.com
            		  Port: 7050
            		  ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer.sdfsdfsdf.com/tls/server.crt
            		  ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer.sdfsdfsdf.com/tls/server.crt
            
            		- Host: orderer1.sdfsdfsdf.com
            		  Port: 7050
            		  ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer1.sdfsdfsdf.com/tls/server.crt
            		  ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer1.sdfsdfsdf.com/tls/server.crt
            
            		- Host: orderer2.sdfsdfsdf.com
            		  Port: 7050
            		  ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer2.sdfsdfsdf.com/tls/server.crt
            		  ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer2.sdfsdfsdf.com/tls/server.crt
            
            		- Host: orderer3.sdfsdfsdf.com
            		  Port: 7050
            		  ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer3.sdfsdfsdf.com/tls/server.crt
            		  ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer3.sdfsdfsdf.com/tls/server.crt
            
            		- Host: orderer4.sdfsdfsdf.com
            		  Port: 7050
            		  ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer4.sdfsdfsdf.com/tls/server.crt
            		  ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer4.sdfsdfsdf.com/tls/server.crt
            
            		- Host: orderer5.sdfsdfsdf.com
            		  Port: 7050
            		  ClientTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer5.sdfsdfsdf.com/tls/server.crt
            		  ServerTLSCert: crypto-config/ordererOrganizations/blackcreek.tech/orderers/orderer5.sdfsdfsdf.com/tls/server.crt
            
            Addresses:
                                
                - orderer.sdfsdfsdf.com:7050                
                - orderer1.sdfsdfsdf.com:7050                
                - orderer2.sdfsdfsdf.com:7050                
                - orderer3.sdfsdfsdf.com:7050                
                - orderer4.sdfsdfsdf.com:7050                
                - orderer5.sdfsdfsdf.com:7050

            Organizations:
            - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *Orderer
        Consortiums:
            sdfsdfsf:
                Organizations:
                
                 - * SDFSDFSDF 
                 - * ADADA 
                 - * ADADAD 
