
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
   

    ca:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
          - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
          - FABRIC_CA_SERVER_CA_NAME=ca-blackcreek
          - FABRIC_CA_SERVER_TLS_ENABLED=true
          - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.blackcreek.tech-cert.pem
          - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA_PRIVATE_KEY}
          - FABRIC_CA_SERVER_PORT=7054

        ports:
          - "6057:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.blackcreek.tech-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA_PRIVATE_KEY} -b admin:adminpw -d'
        volumes:
          - ./crypto-config/peerOrganizations/blackcreek.tech/ca/:/etc/hyperledger/fabric-ca-server-config
          - ./fabric-ca-server/:/etc/hyperledger/fabric-ca-server
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
        container_name: ca.blackcreek.tech
        restart: always
        networks:
          - byfn
        

    ca0:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
          - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
          - FABRIC_CA_SERVER_CA_NAME=ca-dc
          - FABRIC_CA_SERVER_TLS_ENABLED=true
          - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dc.blackcreek.tech-cert.pem
          - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA_PRIVATE_KEY}
          - FABRIC_CA_SERVER_PORT=7054

        ports:
          - "6055:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dc.blackcreek.tech-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA_PRIVATE_KEY} -b admin:adminpw -d'
        volumes:
          - ./crypto-config/peerOrganizations/blackcreek.tech/ca/:/etc/hyperledger/fabric-ca-server-config
          - ./fabric-ca-server/:/etc/hyperledger/fabric-ca-server
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
        container_name: ca.dc.blackcreek.tech
        restart: always
        networks:
          - byfn
        

    ca1:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
          - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
          - FABRIC_CA_SERVER_CA_NAME=ca-dp
          - FABRIC_CA_SERVER_TLS_ENABLED=true
          - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dp.blackcreek.tech-cert.pem
          - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA_PRIVATE_KEY}
          - FABRIC_CA_SERVER_PORT=7054

        ports:
          - "6056:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dp.blackcreek.tech-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA_PRIVATE_KEY} -b admin:adminpw -d'
        volumes:
          - ./crypto-config/peerOrganizations/blackcreek.tech/ca/:/etc/hyperledger/fabric-ca-server-config
          - ./fabric-ca-server/:/etc/hyperledger/fabric-ca-server
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
        container_name: ca.dp.blackcreek.tech
        restart: always
        networks:
          - byfn
        
        